export const VARIABLE_MAP = {
   g_08: 'g_yuu_gd__cleared',
   g_09: 'g__tsugumi_gd_cleared',
   g_0d: 'g_sora_or_tsugumi_gd__cleared',
   g_0e: 'g_sara_or_yuu_gd__cleared',
   g_0f: 'g_tsugumi_gd_cleared',
   g_10: 'g__sora_gd_cleared',
   g_11: 'g_takeshi_ep__cleared',
   g_12: 'g_tsugumi_sora_bd__cleared',
   g_19: 'g_coco_ep__cleared',
   g_0a: 'g_sora_gd_cleared',
   g_0b: 'g_sara_gd__cleared',
   g_0c: 'g__coco_ep_cleared',
   g_13: 'g__yuu_gd_cleared',
   g_14: 'g_yuu_gd_cleared',
   g_15: 'g_yuu_bd_cleared',
   g_16: 'g__sara_gd_cleared',
   g_17: 'g_sara_gd_cleared',
   g_18: 'g_sara_bd_cleared',
   g_1a: 'g_coco_route_unlock',
   g_1b: 'g_kid_bd_cleared',

   l_24: 'coco_route_unlocked',
   l_25: 'yuu_ep_cleared',
   l_26: 'tsugumi_gd_cleared',
   l_27: 'sora_gd_cleared',
   l_28: 'sara_ep_cleared',
   l_29: 'coco_ep_clear',
   l_2a: 'coco_ep_reach_a',
   l_2b: 'coco_ep_reach_b',
   l_2c: 'coco_ep_reach_c',
   l_2d: 'coco_ep_reach_d',
   l_2e: 'coco_ep_reach_e',
   l_2f: 'coco_ep_reach_f',
   l_b0: 'month',
   l_b1: 'day',
   l_b2: 'day2',
   l_b3: 'choice',
   l_b6: 'yuu_point',
   l_b7: 'tsugumi_point',
   l_b8: 'sora_point',
   l_b9: 'sara_point',
   l_ba: 'coco_point',
   l_bb: 'counter',
   l_bc: 'choice_flag1',
   l_bd: 'choice_flag2',
   l_bf: 'accumulator',
   l_c7: 'ending',
   l_d0: 'selection_0_available',
   l_d1: 'selection_1_available',
   l_d2: 'selection_2_available',
   l_d3: 'selection_3_available',
   l_d4: 'selection_4_available',
   l_d5: 'selection_5_available',
   l_d8: 'looked_for_yuu',
   l_d9: 'tsugumi_flag',
   l_da: 'sora_flag',
   l_db: 'repaired_with_sara',
   l_dd: 'listened_to_the_joke',
   l_de: 'blamed_the_tanuki',
   l_df: 'wanted_to_be_called_prince',
   l_e0: 'thought_you_can_swim_34_meters_regardless_water_pressure',
   l_e1: 'went_to_merry_go_round',
   l_e2: 'went_to_warehouse',
   l_e3: 'chose_to_wait_there_in_2nd_day',
   l_e4: 'went_with_yuu_in_2nd_day',
   l_e5: 'chose_almost_completely_vertical',
   l_e6: 'talked_to_yuu_about_her_father_in_6th_day',
   l_e7: 'yuu_gd_flag',
   l_e8: 'said_it_is_not_sora_fault',
   l_e9: 'decide_to_meet_sora_in_2nd_day',
   l_eb: 'made_the_pipe_steam_sound_louder',
   l_ec: 'went_outside_as_sora_suggested_in_3rd_day',
   l_ed: 'confessed_the_truth_in_4th_day',
   l_ee: 'skeptical_about_coco_having_decompression_sickness',
   l_ef: 'went_with_sara_in_3rd_day',
   l_f0: 'know_sora_is_an_ai',
   l_f1: 'is_coco_route',
   l_f2: 'sc2f_cleared',

   sys_f1: 's_shortcut_available',
   sys_f2: 's_jukebox_available',
   sys_f3: 's_album_available',
   sys_f5: 's_clearlist_available',

   dim_ab: 'mono_color_overlay',
   eff_38: 'komore_type',
   eff_3a: 'perspective_direction',
   eff_44: 'number_of_flashes',
   eff_43: 'flash_color',
   eff_13: 'nvl_mode',
   eff_45: 'map_comment_slot',
   eff_46: 'map_comment_index',
   eff_4a: 'map_comment_index_2',

   l_fa: 'scene_title',
} as const;

(() => {
   const testPool = new Set<string>();
   Object.values(VARIABLE_MAP).forEach(e => {
      if (testPool.has(e))
         throw Error(`Duplicated variable: '${e}'`);
      testPool.add(e);
   });
})();

type PropValueOf<T> = T[keyof T];
type VariableMap = typeof VARIABLE_MAP;
type VariableName = PropValueOf<VariableMap>;
type VariableValueMap = Record<number, string>;
type EnumMap = Partial<Record<VariableName, VariableValueMap>>;

export const ENUM_MAP: EnumMap = {
   ending: {
      4: 'SORA_TSUGUMI_BAD_ENDING',
      1: 'SORA_GOOD_ENDING', 0: 'TSUGUMI_GOOD_ENDING',
      3: 'SARA_GOOD_ENDING', 6: 'SARA_BAD_ENDING',
      2: 'YUU_GOOD_ENDING', 5: 'YUU_BAD_ENDING',
   },
   perspective_direction: {
      0: 'FROM_LEFT',
      1: 'FROM_RIGHT',
      2: 'FROM_BOTH',
   },
   nvl_mode: {
      0: 'OFF',
      1: 'ON',
   },
   scene_title: {
      0: 'Prologue  Insell Null',
      1: 'Prologue  Where Is Heaven?',
      2: 'Prologue  Premonitions & Omens',
      3: 'Prologue  Adversity',
      4: 'Takeshi  Erste Boden',
      5: 'Takeshi  Dritte Stock',
      6: 'Takeshi  Zweite Stock',
      7: 'Takeshi  Second Flooding',
      8: 'Takeshi  The Bends',
      9: 'Takeshi  Echo',
      10: 'Takeshi  Ignore Sora',
      11: 'Takeshi  Archimedes\' Principle',
      12: 'Takeshi  Trick',
      13: 'Takeshi  Walking On The Sky',
      14: 'Takeshi  Kick-The-Can',
      15: 'Takeshi  Restoration',
      16: 'Takeshi  Injury',
      17: 'Takeshi  Short Respite',
      18: 'Takeshi  Windblown Sky',
      19: 'Takeshi  Sora\'s Rainbow',
      20: 'Takeshi  Awakening',
      21: 'Takeshi  Useless Struggle',
      22: 'Takeshi  Pygmalion',
      23: 'Takeshi  Spirited Away',
      24: 'Takeshi  Suspicion',
      25: 'Takeshi  Three Paths To Sora',
      26: 'Takeshi  Nibbled Away',
      27: 'Takeshi  Friends',
      28: 'Takeshi  Clawing At The Nest',
      29: 'Takeshi  Until Dawn',
      30: 'Takeshi  Lurking In The Dark',
      31: 'Takeshi  Unknown Clouds',
      32: 'Takeshi  Bonds',
      33: 'Takeshi  Chains',
      34: 'Takeshi  Crisis Point',
      35: 'Takeshi  Dead Or Alive',
      36: 'Takeshi  Fake Sora/Real Sora',
      37: 'Takeshi  Silent Last Supper',
      38: 'Takeshi  Sora\'s Colors...',
      39: 'Takeshi  Showdown And...',
      40: 'Takeshi  Deep Blue',
      41: 'Takeshi  HIMMEL',
      42: 'Takeshi  IBF',
      43: 'Takeshi/Tsugumi  Cure Virus',
      44: 'Takeshi/Tsugumi  Promised Day',
      45: 'Takeshi/Sora  Unknown Rain',
      46: 'Takeshi/Sora  Remembering Sora',
      47: 'Takeshi  Spiel',
      48: 'Takeshi  Geschichte',
      49: 'Kid  Awakening',
      50: 'Kid  Sarasoju',
      51: 'Kid  Reunion Or Chance Meeting?',
      52: 'Kid  Bio Readings',
      53: 'Kid  Hidden Agendas',
      54: 'Kid  The Young Girl',
      55: 'Kid  Pressure Rises And Falls',
      56: 'Kid  Waking and Sleeping',
      57: 'Kid  119 Hours',
      58: 'Kid  Lyric The Mimic',
      59: 'Kid  Hazy Moon In the Darkness',
      60: 'Kid  Inner Truths',
      61: 'Kid  Moon Sprite',
      62: 'Kid  The Return',
      63: 'Kid  Untouchable Moon',
      64: 'Kid  Kick-The-Can',
      65: 'Kid  Morning Ritual',
      66: 'Kid  Nakkyu And Mayo',
      67: 'Kid  Unexpected Harmony',
      68: 'Kid  Encode/Decode',
      69: 'Kid  Restore/Breakdown',
      70: 'Kid  The Moon And Nightmares',
      71: 'Kid  Abnormally Normal',
      72: 'Kid  Collision',
      73: 'Kid  Hypothesis',
      74: 'Kid/You  The 1st Eye',
      75: 'Kid/You  Malakh',
      76: 'Kid/You  Pandora\'s Box',
      77: 'Kid/You  The 2nd Eye',
      78: 'Kid/You  Astral',
      79: 'Kid/You  Gabriel',
      80: 'Kid/You  Yomotsuhirasaka',
      81: 'Kid/You  The 3rd Eye',
      82: 'Kid/You  Babylon',
      83: 'Kid/You  Asmodeus',
      84: 'Kid/You  Mahakala',
      85: 'Kid/You  Raphael',
      86: 'Kid/You  Leviathan',
      87: 'Kid/You  Amrta',
      88: 'Kid/You  Noah\'s ark',
      89: 'Kid/You  Machonom',
      90: 'Kid/You  Shehaqim',
      91: 'Kid/You  Multiverse',
      92: 'Kid/Sara  Eternal',
      93: 'Kid/Sara  Hope',
      94: 'Kid/Sara  Confusion',
      95: 'Kid/Sara  Purification',
      96: 'Kid/Sara  Message',
      97: 'Kid/Sara  Utopia',
      98: 'Kid/Sara  Memory',
      99: 'Kid/Sara  Promises',
      100: 'Kid/Sara  Omen',
      101: 'Kid/Sara  Bonds',
      102: 'Kid/Sara  Merging',
      103: 'Kid/Sara  Future',
      104: 'Coco  Perusing Pictures',
      105: 'Coco  Who Am I, Who Are You?',
      106: 'Coco  Reflecting On The Past',
      107: 'Coco  Battered And Bruised',
      108: 'Coco  Ring Of The Phoenix',
      109: 'Coco  Moonlight Atonement',
      110: 'Coco  Childlike',
      111: 'Coco  Tears Of A Nun',
      112: 'Coco  Mark Of Original Sin',
      113: 'Coco  Potato Bug DJ',
      114: 'Coco  Drama Of The Heart',
      115: 'Coco  Scars Of Love',
      116: 'Coco  34 years',
      117: 'Coco  Power To Dissolve',
      118: 'Coco  4DBW',
      119: 'Coco  Banished From Heaven',
      120: 'Coco  The Descent',
      121: 'Coco  BEWARE OF DOG',
      122: 'Coco  Wake From Eternal Sleep',
      123: 'Coco  Against The Flow Of Time',
      124: 'Coco  Last Awakening',
      125: 'Epilogue  Blick Winkel'
   },
};

Object.keys(ENUM_MAP.scene_title).forEach(k =>
   ENUM_MAP.scene_title[k] = `"${ENUM_MAP.scene_title[k]}"`
);